import javax.swing.JFrame;
import java.util.Arrays;
import java.util.Random;

/**
 * @author RezTheCoward
 * @reconstructed-by Jonathan Zamora
 */
public class ForceModePanel extends javax.swing.JPanel {

    /**
     * Creates new form TotalForcePanel
     */
    public ForceModePanel() {
        initComponents();
        setBackground(Main.baseColor);
        if(Main.multiplayer)
        {
            switch (Main.currentPlayer) {
                case 1:
                    jLabel8.setText(Main.name1);
                    break;
                case 2:
                    jLabel8.setText(Main.name2);
                    break;
                case 3:
                    jLabel8.setText(Main.name3);
                    break;
                case 4:
                    jLabel8.setText(Main.name4);
                    break;
                case 5:
                    jLabel8.setText(Main.name5);
                    break;
                case 6:
                    jLabel8.setText(Main.name6);
                    break;
                default:
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        jButton7 = new javax.swing.JButton();
        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        jButton9 = new javax.swing.JButton();
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton8.setOpaque(false);
        jButton8.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);

        setBackground(new java.awt.Color(0, 0, 55));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-punching-bag-50.png"))); // NOI18N
        jLabel16.setOpaque(true);
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, -1));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-gear-50.png"))); // NOI18N
        jLabel17.setOpaque(true);
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 320, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-50.png"))); // NOI18N
        jLabel11.setOpaque(true);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-graph-50.png"))); // NOI18N
        jLabel18.setOpaque(true);
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 320, -1));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-male-user-50.png"))); // NOI18N
        jLabel19.setOpaque(true);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 320, -1));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-open-door-50.png"))); // NOI18N
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, 320, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, 500, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        jLabel2.setForeground(Main.titleColor);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Force Mode");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 500, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 75)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Force Accrued");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 500, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 75)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Current Time");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 290, 500, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("00:00.0");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 400, 500, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 75)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Force Goal");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 500, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 100)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("15,000");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 500, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(21, 140, 75));
        jButton8.setText("Start");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, 160, 50));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(242, 0, 0));
        jButton7.setText("Stop");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 560, 160, 50));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(246, 225, 17));
        jButton9.setText("Reset");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 560, 160, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(21, 140, 75));
        jButton1.setText("+");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 70, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton3.setForeground(new java.awt.Color(242, 0, 0));
        jButton3.setText("-");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        jButton3.setPreferredSize(new java.awt.Dimension(19, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 70, 60));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 320, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 500, 60));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton10.setText("Done");
        jButton10.setBorder(getBorder());
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 790, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Main.transitionToPage(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private int minute;
    private int second;
    private int ms;
    private boolean start;
    
    public static int[] generateRandNums(int max, int[] randNums){
        Random r = new Random();
        for(int i = 0; i < randNums.length; i++){
            randNums[i] = r.nextInt(max) + 1000;
        }
        Arrays.sort(randNums);
        return randNums;
    }
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        int[] randNumbs = new int [40];
        start = true;
        generateRandNums(14000, randNumbs);
        Thread t;
        t = new Thread(){
            @Override
            @SuppressWarnings("SleepWhileInLoop")
            public void run(){
                while(start == true){
                    try{
                        sleep(10);
                        ms++;
                        if(ms == 100){
                            jLabel1.setText(String.valueOf(randNumbs[second]));
                            second++;
                            ms = 0;
                        }
                        if(second == 60){
                            minute++;
                            second = 0;
                        }
                        String minute_str = String.format("%02d", minute);
                        String second_str = String.format("%02d", second);
                        String ms_str = String.format("%02d", ms);
                        jLabel5.setText(minute_str + ":" + second_str + "." + ms_str);
                    }catch(InterruptedException e){
                        System.out.println("Error");
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        start = false;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        start = false;
        ms = 0;
        second = 0;
        minute = 0;
        jLabel1.setText("0");
        String minute_str = String.format("%02d", minute);
        String second_str = String.format("%02d", second);
        String ms_str = String.format("%02d", ms);
        jLabel5.setText(minute_str + ":" + second_str + "." + ms_str);
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private int goal = 15000;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        goal = goal + 500;
        String increaseGoal = String.format("%,d", goal);
        jLabel7.setText(increaseGoal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(goal > 0){
            goal = goal - 500;
        }
        else {
            goal = 0;
        }
        String decreaseGoal = String.format("%,d", goal);
        jLabel7.setText(decreaseGoal);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        Main.transitionToPage(6);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        if (Main.multiplayer)
        {
            int score = (int)Math.round(Integer.parseInt(jLabel1.getText()) 
                * 0.5 * (ms + second * 1000 + minute * 60000) * 0.5 * 0.001);

            switch (Main.currentPlayer) {
                case 1:
                    Main.score1 = Integer.toString(score);
                    System.out.println((Main.score1));
                    break;
                case 2:
                    Main.score2 = Integer.toString(score);
                    System.out.println((Main.score2));
                    break;
                case 3:
                    Main.score3 = Integer.toString(score);
                    System.out.println((Main.score3));
                    break;
                case 4:
                    Main.score4 = Integer.toString(score);
                    System.out.println((Main.score4));
                    break;
                case 5:
                    Main.score5 = Integer.toString(score);
                    System.out.println((Main.score5));
                    break;
                case 6:
                    Main.score6 = Integer.toString(score);
                    System.out.println((Main.score6));
                    break;
                default:
                    break;
            }

            Main.currentPlayer = Main.currentPlayer + 1;
            System.out.println(Main.currentPlayer);

            if(Main.currentPlayer > Main.playerNum)
            {
                Main.Frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                Main.Frame.setContentPane(new ForceModeMultiplayer(Main.playerNum));
                Main.Frame.repaint();
                Main.Frame.revalidate();
                Main.doneFlag = true ;
            }
            else
            {
                Main.Frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                Main.Frame.setContentPane(new ForceModePanel());
                Main.Frame.repaint();
                Main.Frame.revalidate(); 
            }
        }
        else
        {
            Main.done() ;
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Main.closeFrame();
    }//GEN-LAST:event_jLabel20MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
