/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author RezTheCoward
 */
public class homePagePanel extends javax.swing.JPanel {

    /**
     * Creates new form homePagePanel
     */
    Timer timer;
    public homePagePanel() {
        initComponents();
        ActionListener actionListener = (ActionEvent evt) -> {
            Date date = new Date();
            DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
            String time = timeFormat.format(date);
            jLabel7.setText(time);
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
        setBackground(Main.baseColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        TimedMode_text = new javax.swing.JLabel();
        TimedModeTraining_Button = new javax.swing.JButton();
        TimedModeTraining_Button.setOpaque(false);
        TimedModeTraining_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        PunchChallenge_text = new javax.swing.JLabel();
        ForceModeMultiplayer_Button = new javax.swing.JButton();
        ForceModeMultiplayer_Button.setOpaque(false);
        ForceModeMultiplayer_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        StrengthModeTraining_Button = new javax.swing.JButton();
        StrengthModeTraining_Button.setOpaque(false);
        StrengthModeTraining_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        ComboModeMultiplayer_Button = new javax.swing.JButton();
        ComboModeMultiplayer_Button.setOpaque(false);
        ComboModeMultiplayer_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        ForceMode_text = new javax.swing.JLabel();
        ForceModeTraining_Button = new javax.swing.JButton();
        ForceModeTraining_Button.setOpaque(false);
        ForceModeTraining_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        TimedModeMultiplayer_Button = new javax.swing.JButton();
        TimedModeMultiplayer_Button.setOpaque(false);
        TimedModeMultiplayer_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        ComboMode_text = new javax.swing.JLabel();
        ComboModeTraining_Button = new javax.swing.JButton();
        ComboModeTraining_Button.setOpaque(false);
        ComboModeTraining_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        StrengthModeMultiplayer_Button = new javax.swing.JButton();
        StrengthModeMultiplayer_Button.setOpaque(false);
        StrengthModeMultiplayer_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Competition_text = new javax.swing.JLabel();
        StrengthMode_text = new javax.swing.JLabel();
        History_Button = new javax.swing.JButton();
        History_Button.setOpaque(false);
        History_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        SensorAdjustment_Button = new javax.swing.JButton();
        SensorAdjustment_Button.setOpaque(false);
        SensorAdjustment_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        PunchChallengeTraining_Button = new javax.swing.JButton();
        PunchChallengeTraining_Button.setOpaque(false);
        PunchChallengeTraining_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        PunchChallengeMultiplayer_Button = new javax.swing.JButton();
        PunchChallengeMultiplayer_Button.setOpaque(false);
        PunchChallengeMultiplayer_Button.setContentAreaFilled(false);
        //jButton1.setBorderPainted(false);
        Exit_Icon = new javax.swing.JLabel();
        Home_Icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Settings_Icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setBackground(new java.awt.Color(0, 0, 55));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Timer");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 140, 100, -1));

        TimedMode_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        TimedMode_text.setForeground(new java.awt.Color(240, 240, 240));
        TimedMode_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimedMode_text.setText("Timed Mode");
        add(TimedMode_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 275, 340, 50));

        TimedModeTraining_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TimedModeTraining_Button.setForeground(new java.awt.Color(240, 240, 240));
        TimedModeTraining_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        TimedModeTraining_Button.setLabel("Training");
        TimedModeTraining_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimedModeTraining_ButtonActionPerformed(evt);
            }
        });
        add(TimedModeTraining_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 200, 60));

        PunchChallenge_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        PunchChallenge_text.setForeground(new java.awt.Color(240, 240, 240));
        PunchChallenge_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PunchChallenge_text.setText("Punch Challenge");
        add(PunchChallenge_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 665, 340, 50));

        ForceModeMultiplayer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ForceModeMultiplayer_Button.setForeground(new java.awt.Color(240, 240, 240));
        ForceModeMultiplayer_Button.setText("Multiplayer");
        ForceModeMultiplayer_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        ForceModeMultiplayer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForceModeMultiplayer_ButtonActionPerformed(evt);
            }
        });
        add(ForceModeMultiplayer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 200, 60));

        StrengthModeTraining_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        StrengthModeTraining_Button.setForeground(new java.awt.Color(240, 240, 240));
        StrengthModeTraining_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        StrengthModeTraining_Button.setLabel("Training");
        StrengthModeTraining_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrengthModeTraining_ButtonActionPerformed(evt);
            }
        });
        add(StrengthModeTraining_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 770, 200, 60));

        ComboModeMultiplayer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboModeMultiplayer_Button.setForeground(new java.awt.Color(240, 240, 240));
        ComboModeMultiplayer_Button.setText("Multiplayer");
        ComboModeMultiplayer_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        ComboModeMultiplayer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboModeMultiplayer_ButtonActionPerformed(evt);
            }
        });
        add(ComboModeMultiplayer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 200, 60));

        ForceMode_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        ForceMode_text.setForeground(new java.awt.Color(240, 240, 240));
        ForceMode_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForceMode_text.setText("Force Mode");
        add(ForceMode_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 275, 340, 50));

        ForceModeTraining_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ForceModeTraining_Button.setForeground(new java.awt.Color(240, 240, 240));
        ForceModeTraining_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        ForceModeTraining_Button.setLabel("Training");
        ForceModeTraining_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForceModeTraining_ButtonActionPerformed(evt);
            }
        });
        add(ForceModeTraining_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 200, 60));

        TimedModeMultiplayer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TimedModeMultiplayer_Button.setForeground(new java.awt.Color(240, 240, 240));
        TimedModeMultiplayer_Button.setText("Multiplayer");
        TimedModeMultiplayer_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        TimedModeMultiplayer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimedModeMultiplayer_ButtonActionPerformed(evt);
            }
        });
        add(TimedModeMultiplayer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 500, 200, 60));

        ComboMode_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        ComboMode_text.setForeground(new java.awt.Color(240, 240, 240));
        ComboMode_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComboMode_text.setText("Combo Mode");
        add(ComboMode_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 275, 340, 50));

        ComboModeTraining_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ComboModeTraining_Button.setForeground(new java.awt.Color(240, 240, 240));
        ComboModeTraining_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        ComboModeTraining_Button.setLabel("Training");
        ComboModeTraining_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboModeTraining_ButtonActionPerformed(evt);
            }
        });
        add(ComboModeTraining_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 60));

        StrengthModeMultiplayer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        StrengthModeMultiplayer_Button.setForeground(new java.awt.Color(240, 240, 240));
        StrengthModeMultiplayer_Button.setText("Multiplayer");
        StrengthModeMultiplayer_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        StrengthModeMultiplayer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrengthModeMultiplayer_ButtonActionPerformed(evt);
            }
        });
        add(StrengthModeMultiplayer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 900, 200, 60));

        Competition_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        Competition_text.setForeground(new java.awt.Color(240, 240, 240));
        Competition_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Competition_text.setText("Competition");
        add(Competition_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 665, 340, 50));

        StrengthMode_text.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        StrengthMode_text.setForeground(new java.awt.Color(240, 240, 240));
        StrengthMode_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StrengthMode_text.setText("Strength Mode");
        add(StrengthMode_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 665, 340, 50));

        History_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        History_Button.setForeground(new java.awt.Color(240, 240, 240));
        History_Button.setText("History");
        History_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        History_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                History_ButtonActionPerformed(evt);
            }
        });
        add(History_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 770, 200, 60));

        SensorAdjustment_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SensorAdjustment_Button.setForeground(new java.awt.Color(240, 240, 240));
        SensorAdjustment_Button.setText("Sensor Adjustment");
        SensorAdjustment_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        SensorAdjustment_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SensorAdjustment_ButtonActionPerformed(evt);
            }
        });
        add(SensorAdjustment_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 900, 220, 60));

        PunchChallengeTraining_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PunchChallengeTraining_Button.setForeground(new java.awt.Color(240, 240, 240));
        PunchChallengeTraining_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        PunchChallengeTraining_Button.setLabel("Training");
        PunchChallengeTraining_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunchChallengeTraining_ButtonActionPerformed(evt);
            }
        });
        add(PunchChallengeTraining_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 770, 200, 60));

        PunchChallengeMultiplayer_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PunchChallengeMultiplayer_Button.setForeground(new java.awt.Color(240, 240, 240));
        PunchChallengeMultiplayer_Button.setText("Multiplayer");
        PunchChallengeMultiplayer_Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(173, 216, 230)));
        PunchChallengeMultiplayer_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunchChallengeMultiplayer_ButtonActionPerformed(evt);
            }
        });
        add(PunchChallengeMultiplayer_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 900, 200, 60));

        Exit_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-open-door-50.png"))); // NOI18N
        Exit_Icon.setOpaque(true);
        Exit_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit_IconMouseClicked(evt);
            }
        });
        add(Exit_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, 320, -1));

        Home_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-50.png"))); // NOI18N
        Home_Icon.setOpaque(true);
        Home_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_IconMouseClicked(evt);
            }
        });
        add(Home_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-punching-bag-50.png"))); // NOI18N
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, -1));

        Settings_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-gear-50.png"))); // NOI18N
        Settings_Icon.setOpaque(true);
        Settings_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings_IconMouseClicked(evt);
            }
        });
        add(Settings_Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 320, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-graph-50.png"))); // NOI18N
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 320, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-male-user-50.png"))); // NOI18N
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 320, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TimedModeTraining_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimedModeTraining_ButtonActionPerformed
        Main.transitionToPage(4);
    }//GEN-LAST:event_TimedModeTraining_ButtonActionPerformed

    private void ForceModeMultiplayer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForceModeMultiplayer_ButtonActionPerformed
        Main.transitionToMulti(0, 1);
    }//GEN-LAST:event_ForceModeMultiplayer_ButtonActionPerformed

    private void StrengthModeTraining_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrengthModeTraining_ButtonActionPerformed
        Main.transitionToPage(5);
    }//GEN-LAST:event_StrengthModeTraining_ButtonActionPerformed

    private void ComboModeMultiplayer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboModeMultiplayer_ButtonActionPerformed
        
    }//GEN-LAST:event_ComboModeMultiplayer_ButtonActionPerformed

    private void ForceModeTraining_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForceModeTraining_ButtonActionPerformed
        
        Main.transitionToPage(3);
    }//GEN-LAST:event_ForceModeTraining_ButtonActionPerformed

    private void TimedModeMultiplayer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimedModeMultiplayer_ButtonActionPerformed
        
    }//GEN-LAST:event_TimedModeMultiplayer_ButtonActionPerformed

    private void ComboModeTraining_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboModeTraining_ButtonActionPerformed
        
        Main.transitionToPage(2);
    }//GEN-LAST:event_ComboModeTraining_ButtonActionPerformed

    private void StrengthModeMultiplayer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrengthModeMultiplayer_ButtonActionPerformed
        
    }//GEN-LAST:event_StrengthModeMultiplayer_ButtonActionPerformed

    private void History_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_History_ButtonActionPerformed
        
    }//GEN-LAST:event_History_ButtonActionPerformed

    private void SensorAdjustment_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SensorAdjustment_ButtonActionPerformed
        
        Main.transitionToPage(6);
    }//GEN-LAST:event_SensorAdjustment_ButtonActionPerformed

    private void PunchChallengeTraining_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunchChallengeTraining_ButtonActionPerformed
        
    }//GEN-LAST:event_PunchChallengeTraining_ButtonActionPerformed

    private void PunchChallengeMultiplayer_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunchChallengeMultiplayer_ButtonActionPerformed
        
    }//GEN-LAST:event_PunchChallengeMultiplayer_ButtonActionPerformed

    private void Exit_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_IconMouseClicked
        
        Main.closeFrame();
    }//GEN-LAST:event_Exit_IconMouseClicked

    private void Home_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_IconMouseClicked
        Main.transitionToPage(1);
    }//GEN-LAST:event_Home_IconMouseClicked

    private void Settings_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings_IconMouseClicked
        Main.transitionToPage(6);
    }//GEN-LAST:event_Settings_IconMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComboModeMultiplayer_Button;
    private javax.swing.JButton ComboModeTraining_Button;
    private javax.swing.JLabel ComboMode_text;
    private javax.swing.JLabel Competition_text;
    private javax.swing.JLabel Exit_Icon;
    private javax.swing.JButton ForceModeMultiplayer_Button;
    private javax.swing.JButton ForceModeTraining_Button;
    private javax.swing.JLabel ForceMode_text;
    private javax.swing.JButton History_Button;
    private javax.swing.JLabel Home_Icon;
    private javax.swing.JButton PunchChallengeMultiplayer_Button;
    private javax.swing.JButton PunchChallengeTraining_Button;
    private javax.swing.JLabel PunchChallenge_text;
    private javax.swing.JButton SensorAdjustment_Button;
    private javax.swing.JLabel Settings_Icon;
    private javax.swing.JButton StrengthModeMultiplayer_Button;
    private javax.swing.JButton StrengthModeTraining_Button;
    private javax.swing.JLabel StrengthMode_text;
    private javax.swing.JButton TimedModeMultiplayer_Button;
    private javax.swing.JButton TimedModeTraining_Button;
    private javax.swing.JLabel TimedMode_text;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
