/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modes.Setup;

import Main.Main;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Ylope
 */
public class ComboModeSetup1 extends javax.swing.JPanel {

    int forceGoal = 500;
    int numPlayers = 6;
    boolean countDown = true;
    boolean multiplayer = false;
        
    /**
     * Creates new form ComboModeSetup1
     */
    public ComboModeSetup1() {
        initComponents();
        
        //SideBar.setVisible(false);
        ForceGoalMinus.setVisible(false);
        ForceGoalPlus.setVisible(false);
        NumOfPlayers.setVisible(false);
        NumOfPlayersText.setVisible(false);
        NumPlayersPlus.setVisible(false);
        NumPlayersMinus.setVisible(false);
        Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SidebarButton = new javax.swing.JLabel();
        ComboCounterTitle = new javax.swing.JLabel();
        PunchChallengeButton = new javax.swing.JLabel();
        ComboModeB = new javax.swing.JLabel();
        TimedModeButton = new javax.swing.JLabel();
        ForceModeButtom = new javax.swing.JLabel();
        StrengthModeButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboModeTitle = new javax.swing.JLabel();
        ForceGoal = new javax.swing.JLabel();
        ForceGoalPlus = new javax.swing.JLabel();
        ForceGoalMinus = new javax.swing.JLabel();
        Training_Button = new javax.swing.JLabel();
        NumOfPlayersText = new javax.swing.JLabel();
        NumOfPlayers = new javax.swing.JLabel();
        NumPlayersPlus = new javax.swing.JLabel();
        NumPlayersMinus = new javax.swing.JLabel();
        Competition_Button = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 55));
        setMaximumSize(new java.awt.Dimension(768, 1024));
        setMinimumSize(new java.awt.Dimension(768, 1024));

        jPanel1.setBackground(new java.awt.Color(0, 0, 55));
        jPanel1.setMaximumSize(new java.awt.Dimension(768, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(768, 1024));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidebarButton.setBackground(new java.awt.Color(51, 51, 56));
        SidebarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SidebarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menuIcon.png"))); // NOI18N
        SidebarButton.setOpaque(true);
        SidebarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(SidebarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 55));

        ComboCounterTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ComboCounterTitle.setForeground(new java.awt.Color(240, 240, 240));
        ComboCounterTitle.setText("ComboCounter");
        jPanel2.add(ComboCounterTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        PunchChallengeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N

        ComboModeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/filledCircleIcon.png"))); // NOI18N

        TimedModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        TimedModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimedModeButtonMouseClicked(evt);
            }
        });

        ForceModeButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        ForceModeButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceModeButtomMouseClicked(evt);
            }
        });

        StrengthModeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/emptyCircleIcon.png"))); // NOI18N
        StrengthModeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StrengthModeButtonMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Force Goal");

        ComboModeTitle.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        ComboModeTitle.setForeground(new java.awt.Color(240, 240, 240));
        ComboModeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ComboModeTitle.setText("Combo Mode");

        ForceGoal.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ForceGoal.setForeground(new java.awt.Color(240, 240, 240));
        ForceGoal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ForceGoal.setText("500");
        ForceGoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalMouseClicked(evt);
            }
        });

        ForceGoalPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plusIcon.png"))); // NOI18N
        ForceGoalPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalPlusMouseClicked(evt);
            }
        });

        ForceGoalMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minusIcon.png"))); // NOI18N
        ForceGoalMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForceGoalMinusMouseClicked(evt);
            }
        });

        Training_Button.setBackground(new java.awt.Color(51, 51, 56));
        Training_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Training_Button.setForeground(new java.awt.Color(240, 240, 240));
        Training_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Training_Button.setText("Training");
        Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Training_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Training_ButtonMouseClicked(evt);
            }
        });

        NumOfPlayersText.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        NumOfPlayersText.setForeground(new java.awt.Color(240, 240, 240));
        NumOfPlayersText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfPlayersText.setText("# of Players:");

        NumOfPlayers.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        NumOfPlayers.setForeground(new java.awt.Color(240, 240, 240));
        NumOfPlayers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOfPlayers.setText("2");

        NumPlayersPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circlePlusIcon.png"))); // NOI18N
        NumPlayersPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumPlayersPlusMouseClicked(evt);
            }
        });

        NumPlayersMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circleMinusIcon.png"))); // NOI18N
        NumPlayersMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumPlayersMinusMouseClicked(evt);
            }
        });

        Competition_Button.setBackground(new java.awt.Color(51, 51, 56));
        Competition_Button.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Competition_Button.setForeground(new java.awt.Color(240, 240, 240));
        Competition_Button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Competition_Button.setText("Competition");
        Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Competition_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Competition_ButtonMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Player Setting");

        StartButton.setBackground(new java.awt.Color(51, 51, 56));
        StartButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        StartButton.setForeground(new java.awt.Color(240, 240, 240));
        StartButton.setText("Start");
        StartButton.setContentAreaFilled(false);
        StartButton.setFocusPainted(false);
        StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(ComboModeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(ComboModeB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ForceModeButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TimedModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(290, 290, 290)
                                    .addComponent(PunchChallengeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(ForceGoalMinus)
                                    .addGap(95, 95, 95)
                                    .addComponent(ForceGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Training_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(80, 80, 80)
                            .addComponent(ForceGoalPlus))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(Competition_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(StrengthModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(115, 128, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumOfPlayersText, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(210, 210, 210)
                                    .addComponent(NumOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addComponent(NumPlayersPlus)
                            .addGap(0, 0, 0)
                            .addComponent(NumPlayersMinus))
                        .addComponent(StartButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ComboModeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboModeB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForceModeButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimedModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(807, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(280, 313, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(PunchChallengeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ForceGoalMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ForceGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(180, 180, 180)
                            .addComponent(Training_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ForceGoalPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Competition_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StrengthModeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(40, 40, 40)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NumOfPlayersText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NumPlayersPlus)
                                .addComponent(NumPlayersMinus))))
                    .addGap(60, 60, 60)
                    .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SidebarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarButtonMouseClicked
        
    }//GEN-LAST:event_SidebarButtonMouseClicked

    private void TimedModeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimedModeButtonMouseClicked
        Main.setup(3);
    }//GEN-LAST:event_TimedModeButtonMouseClicked

    private void ForceModeButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceModeButtomMouseClicked
        // TODO add your handling code here:
        Main.setup(2);
    }//GEN-LAST:event_ForceModeButtomMouseClicked

    private void StrengthModeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StrengthModeButtonMouseClicked
        // TODO add your handling code here:
        Main.setup(4);
    }//GEN-LAST:event_StrengthModeButtonMouseClicked

    private void ForceGoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalMouseClicked
        ForceGoalMinus.setVisible(true);
        ForceGoalPlus.setVisible(true);
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                ForceGoalMinus.setVisible(false);
                ForceGoalPlus.setVisible(false);
            }
        };
        Timer timer = new Timer(7000, taskPerformer);
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ForceGoalMouseClicked

    private void ForceGoalPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalPlusMouseClicked
        if (forceGoal < 3000)
        {
            forceGoal += 500;
        }
        else if (forceGoal < 10000)
        {
            forceGoal += 1000;
        }
        else if (forceGoal < 100000)
        {
            forceGoal += 5000;
        }
        ForceGoal.setText(String.format("%,d", forceGoal));
    }//GEN-LAST:event_ForceGoalPlusMouseClicked

    private void ForceGoalMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForceGoalMinusMouseClicked
        if (forceGoal <= 3000)
        {
            forceGoal -= 500;
        }
        else if (forceGoal <= 10000)
        {
            forceGoal -= 1000;
        }
        else if (forceGoal <= 100000)
        {
            forceGoal -= 5000;
        }
        String frcGoal = String.valueOf(forceGoal);
        ForceGoal.setText(frcGoal);
    }//GEN-LAST:event_ForceGoalMinusMouseClicked

    private void Training_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Training_ButtonMouseClicked
        if (multiplayer == true)
        {
            multiplayer = false ;
            Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

            // Removes # of Players Visibility
            NumOfPlayersText.setVisible(false);
            NumOfPlayers.setVisible(false);
            NumPlayersPlus.setVisible(false);
            NumPlayersMinus.setVisible(false);
        }
    }//GEN-LAST:event_Training_ButtonMouseClicked

    private void NumPlayersPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumPlayersPlusMouseClicked
        if (Main.playerNum < 10)
        {
            Main.playerNum++;
            String num = String.valueOf(Main.playerNum);
            NumOfPlayers.setText(num);
        }
    }//GEN-LAST:event_NumPlayersPlusMouseClicked

    private void NumPlayersMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumPlayersMinusMouseClicked
        if (Main.playerNum > 2)
        {
            Main.playerNum--;
            String num = String.valueOf(Main.playerNum);
            NumOfPlayers.setText(num);
        }
    }//GEN-LAST:event_NumPlayersMinusMouseClicked

    private void Competition_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Competition_ButtonMouseClicked
        if (multiplayer == false)
        {
            multiplayer = true ;
            Competition_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
            Training_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

            // Visiblity to add players
            NumOfPlayersText.setVisible(true);
            NumOfPlayers.setVisible(true);
            NumPlayersPlus.setVisible(true);
            NumPlayersMinus.setVisible(true);

        }
    }//GEN-LAST:event_Competition_ButtonMouseClicked

    private void StartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartButtonMouseClicked
        if (multiplayer == false)
        //Main.createForceMode(forceGoal);
        //else
        {
            Main.multiplayer(numPlayers);
        }
    }//GEN-LAST:event_StartButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComboCounterTitle;
    private javax.swing.JLabel ComboModeB;
    private javax.swing.JLabel ComboModeTitle;
    private javax.swing.JLabel Competition_Button;
    private javax.swing.JLabel ForceGoal;
    private javax.swing.JLabel ForceGoalMinus;
    private javax.swing.JLabel ForceGoalPlus;
    private javax.swing.JLabel ForceModeButtom;
    private javax.swing.JLabel NumOfPlayers;
    private javax.swing.JLabel NumOfPlayersText;
    private javax.swing.JLabel NumPlayersMinus;
    private javax.swing.JLabel NumPlayersPlus;
    private javax.swing.JLabel PunchChallengeButton;
    private javax.swing.JLabel SidebarButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel StrengthModeButton;
    private javax.swing.JLabel TimedModeButton;
    private javax.swing.JLabel Training_Button;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
